apiVersion: v2
name: argocd-mcp
description: OpenAPI-driven MCP server that exposes the entire ArgoCD API to LLMs
type: application
version: 1.4.0
appVersion: 1.4.0
home: https://github.com/matthisholleville/argocd-mcp
sources:
  - https://github.com/matthisholleville/argocd-mcp
maintainers:
  - name: matthisholleville
    url: https://github.com/matthisholleville
keywords:
  - argocd
  - mcp
  - llm
  - ai
  - gitops
dependencies:
  - name: ollama
    version: 1.52.0
    repository: https://otwld.github.io/ollama-helm/
    condition: embeddings.enabled
